name: Deploy develop branch
on:
  pull_request:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: deploy develop branch
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/search
            npm install
            sudo git pull origin develop
